### PR TITLE
fix: use raw GTFS direction_id for schedule/stops-for-route groupings

### LINKED ISSUE #882: fix(schedule-for-route): use raw GTFS direction_id as stopTripGrouping id
## Problem

/schedule-for-route (and /stops-for-route) returned directionId: "0" for trips whose GTFS direction_id=1, and vice versa — stops/trips are paired with the wrong direction label. Confirmed against Java reference on unitrans_E.

### PR DESCRIPTION
**Pull request by Ahmedhossamdev**
Fixes: #882

## Summary
- `groupTripsByDirection` re-indexed groups (descending sort), swapping CSV `direction_id` 0 ↔ 1 in the response.
- Use the raw GTFS `direction_id` string as the group id (Java parity).
- Sort `stops-for-route` stopGroups by headsign name (Java parity).

## Summary by CodeRabbit

* **Bug Fixes**
  * Stop groups are now ordered by stop/route names for more consistent display.
  * Direction groups are ordered and identified by ascending direction ID for more predictable grouping and accurate trip-to-direction matching.

* **Tests**
  * Updated tests to precisely assert direction-to-group and stop-group assignments and reflect the new ordering and ID behavior.

### CODE REVIEW

File: internal/restapi/schedule_for_route_handler_test.go [hunk 1]
```diff
@@ -218,38 +214,44 @@ func TestScheduleForRouteHandler_DirectionIDJavaParity(t *testing.T) {
 	require.Equal(t, http.StatusOK, resp.StatusCode)
 
 	data, ok := model.Data.(map[string]interface{})
-	require.True(t, ok)
+	require.True(t, ok, "model.Data should be a map")
```
Comment (fletcherw) [inline internal/restapi/schedule_for_route_handler_test.go]: I don't think these extra comments on the assertions are required, this can be inferred from the previous line.

Another option is to convert this test to use typed responses like in #862 to simplify further.

File: internal/restapi/schedule_for_route_handler_test.go [hunk 2]
```diff
@@ -218,38 +214,44 @@ func TestScheduleForRouteHandler_DirectionIDJavaParity(t *testing.T) {
...
 	entry, ok := data["entry"].(map[string]interface{})
-	require.True(t, ok)
-
+	require.True(t, ok, "entry should be a map")
 	groupings, ok := entry["stopTripGroupings"].([]interface{})
-	require.True(t, ok)
-	require.Len(t, groupings, 2, "route 25_1885 has trips in both directions")
```
Comment (fletcherw) [inline internal/restapi/schedule_for_route_handler_test.go:227]: why did you delete this comment, I think this is useful context.

File: internal/restapi/stops_for_route_handler.go [hunk 3]
```diff
@@ -342,7 +343,7 @@ func processTripGroups(
 
 	if len(allStopGroups) > 0 {
 		sort.Slice(allStopGroups, func(i, j int) bool {
-			return allStopGroups[i].ID < allStopGroups[j].ID
+			return strings.Join(allStopGroups[i].Name.Names, "") < strings.Join(allStopGroups[j].Name.Names, "")
```
Comment (fletcherw) [inline internal/restapi/stops_for_route_handler.go]: this feels like a strange way to sort, are the stopGroups names in a consistent order?

**Review by fletcherw — APPROVED** [review]

File: internal/restapi/stops_for_route_handler.go (hunk 3 above)
Comment (Ahmedhossamdev) [reply internal/restapi/stops_for_route_handler.go]: Yep. Names is always a single-element slice here (populated once with []string{groupHeadsign}), so the order is consistent. I can simplify it to sort by Name.Name directly.

File: internal/restapi/schedule_for_route_handler_test.go (hunk 2 above)
Comment (Ahmedhossamdev) [reply internal/restapi/schedule_for_route_handler_test.go:227]: Fair point, I'll restore it, I was trying with different routeIds (:
